<?php
$typeArr[2] = '织梦源码';
$typeArr[3] = 'Web技术';
$typeArr[4] = '织梦教程';
$typeArr[5] = 'Discuz教程';
$typeArr[6] = 'Discuz模板';
$typeArr[7] = 'wordpress主题';
$typeArr[8] = 'phpcms模板';
$typeArr[9] = 'phpwind模板';
$typeArr[10] = 'ecshop模板';
$typeArr[12] = '帝国模板';
$typeArr[13] = 'wordpress教程';
$typeArr[14] = 'ecshop教程';
$typeArr[15] = '各类模板';
$typeArr[17] = '站长学院';
$typeArr[18] = '网站seo';
$typeArr[19] = '建站资讯';
$typeArr[20] = 'html模板';
$typeArr[21] = '模板提交';
$typeArr[22] = 'discuz插件';
$typeArr[23] = '手机网站模板';
$typeArr[24] = '免费源码';
$typeArr[26] = '任务接单';
$typeArr[27] = 'VIP专区';
?>