<section> <a href="[field:arcurl/]" target="_blank"><img class="pngfix" alt="[field:title/]" src="[field:litpic/]" width="250" height="250"></a>
                <div class="text">
                  <h2>[field:title/]</h2>
                  <p class="copy">[field:description function='cn_substr(@me,80)'/]...</p>
                  <p class="button"><a onclick="_gaq.push(['_trackPageview', '#']);" href="[field:arcurl/]" target="_blank">模板详情</a> <a class="dimmed" onclick="_gaq.push(['_trackPageview', '#']);" href="[field:syanshi/]" target="_blank">查看演示</a></p>
                </div>
           </section>