<field:softlinks  itemname="Èí¼þµØÖ·" type="softlinks" isnull="true" default="" rename="" />	
<field:sbm itemname="ÓïÑÔ±àÂë" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:sbm>
<field:sys itemname="Ä£°åÑÕÉ«" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:sys>
<field:ssy itemname="ÊÊÓÃÕ¾µã" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:ssy>
<field:syanshi itemname="ÑÝÊ¾ÍøÕ¾" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:syanshi>

<field:introduce  itemname="ÏêÏ¸½éÉÜ" type="htmltext" isnull="trnue" default="" rename="" />	