<?php
$z[0]=Array("field","",253,272);
$z[0][4]['name']="title";
$z[1]=Array("field","",337,366);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",406,464);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("global","",966,992);
$z[3][4]['name']="cfg_cmspath";
$z[4]=Array("include","",1217,1262);
$z[4][4]['filename']="plus/highlight.htm";
$z[5]=Array("include","",1281,1317);
$z[5][4]['filename']="head2.htm";
$z[6]=Array("field","",1485,1507);
$z[6][4]['name']="position";
$z[7]=Array("channel","\r\n                 <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                 ",2445,2591);
$z[7][4]['type']="son";
$z[7][4]['typeid']="3";
$z[8]=Array("channel","\r\n                 <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                 ",2962,3109);
$z[8][4]['type']="son";
$z[8][4]['typeid']="17";
$z[9]=Array("field","",3681,3700);
$z[9][4]['name']="title";
$z[10]=Array("field","",3755,3812);
$z[10][4]['name']="pubdate";
$z[10][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[11]=Array("field","",3867,3885);
$z[11][4]['name']="body";
$z[12]=Array("prenext","",4065,4090);
$z[12][4]['get']="pre";
$z[13]=Array("prenext","",4137,4163);
$z[13][4]['get']="next";
$z[14]=Array("include","",4460,4495);
$z[14][4]['filename']="foot.htm";

?>