<?php
$z[0]=Array("field","",47,66);
$z[0][4]['name']="title";
$z[1]=Array("field","",131,160);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",200,258);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("field","",875,897);
$z[3][4]['name']="typename";
$z[4]=Array("field","",1473,1492);
$z[4][4]['name']="title";
$z[5]=Array("field","",1588,1604);
$z[5][4]['name']="id";
$z[6]=Array("field","",1609,1626);
$z[6][4]['name']="mid";
$z[7]=Array("field","",1702,1759);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[8]=Array("field","",1811,1829);
$z[8][4]['name']="body";
$z[9]=Array("arclist","\r\n	<div class=\"topic\">\r\n		<ul class=\"cont-list\">\r\n			<li>\r\n				<span class=\"live-icon\">[field:typename/]</span><a href=\"view.php?aid=[field:id/]\">[field:title/]</a>\r\n			</li>\r\n		</ul>\r\n	</div>\r\n    ",2875,3151);
$z[9][4]['titlelen']="36";
$z[9][4]['typeid']="24";
$z[9][4]['row']="3";
$z[9][4]['orderby']="rand";

?>