<ul id="hot2s[field:global name=autoindex runphp="yes"]@me=@me;[/field:global]" onmouseover="show_goodspic([field:global name=autoindex runphp="yes"]@me=@me;[/field:global],'hot2')">
                <span>[field:global name=autoindex runphp="yes"]@me=@me;[/field:global]</span>
                <p class="name"><a title="[field:title/]" href="[field:arcurl/]">[field:title/]</a></p>
              </ul>
              <ul class="clearfix ul_box" id=hot2b[field:global name=autoindex runphp="yes"]@me=@me;[/field:global] style="display:none">
                <span>[field:global name=autoindex runphp="yes"]@me=@me;[/field:global]</span>
                <li class="img"><a href="[field:arcurl/]"><img alt="[field:title/]" src="[field:litpic/]"></a></li>
                <li><a title="[field:title/]" href="[field:arcurl/]">[field:title/]</a><br>
                  <font class="f1">[field:typename/]</font>
                </li>
              </ul>