<div class="goodsItem_kuang2">
              <div class="goodsItem" onmouseover="this.className='goodsItem goodsItem_on'" onmouseout="this.className='goodsItem'">
                <div class="fj"><a class="fj_a1" href="[field:arcurl/]" target="_blank"><span class="biao pngfix"></span><span>œÍ«ÈΩÈ…‹</span></a></div>
                <a href="[field:arcurl/]" target="_blank"><img class="goodsimg" alt="[field:title/]" src="[field:litpic/]" width="220" height="220"></a><br>
                <p> <a title="[field:title/]" href="[field:arcurl/]" target="_blank">[field:title/]</a></p>
                <div class="clearfix"><font class="f1">[field:typename/]</font><span class="pinlun">[field:pubdate function='strftime("%Y-%m-%d",@me)'/]</span> </div>
              </div>
            </div>