<?php
$z[0]=Array("field","",253,272);
$z[0][4]['name']="title";
$z[1]=Array("field","",352,381);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",421,479);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("global","",981,1007);
$z[3][4]['name']="cfg_cmspath";
$z[4]=Array("include","",1249,1285);
$z[4][4]['filename']="head2.htm";
$z[5]=Array("field","",1455,1477);
$z[5][4]['name']="position";
$z[6]=Array("channel","\r\n      <a title=\"[field:typename/]\" href=\"[field:typeurl/]\">[field:typename/]</a>\r\n      ",1604,1734);
$z[6][4]['type']="son";
$z[7]=Array("list","\r\n      <div class=\"goodsItem_kuang2\">\r\n              <div class=\"goodsItem\" onmouseover=\"this.className='goodsItem goodsItem_on'\" onmouseout=\"this.className='goodsItem'\">\r\n                <div class=\"fj\"><a class=\"fj_a1\" href=\"[field:arcurl/]\" target=\"_blank\"><span class=\"biao pngfix\"></span><span>œÍ«ÈΩÈ…‹</span></a></div>\r\n                <a href=\"[field:arcurl/]\" target=\"_blank\"><img class=\"goodsimg\" alt=\"[field:title/]\" src=\"[field:litpic/]\" width=\"220\" height=\"220\"></a><br>\r\n                <p> <a title=\"[field:title/]\" href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></p>\r\n               <div class=\"clearfix\"><font class=\"f1\">[field:typename/]</font><span class=\"pinlun\">[field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/]</span> </div>\r\n              </div>\r\n            </div>\r\n      ",2392,3252);
$z[7][4]['pagesize']="15";
$z[7][4]['titlelen']="36";
$z[8]=Array("pagelist","",3319,3385);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[8][4]['listsize']="7";
$z[9]=Array("include","",3548,3583);
$z[9][4]['filename']="foot.htm";

?>