<?php
$z[0]=Array("field","",253,272);
$z[0][4]['name']="title";
$z[1]=Array("field","",352,381);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",421,479);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("global","",981,1007);
$z[3][4]['name']="cfg_cmspath";
$z[4]=Array("include","",1249,1285);
$z[4][4]['filename']="head2.htm";
$z[5]=Array("field","",1453,1475);
$z[5][4]['name']="position";
$z[6]=Array("channel","\r\n                 <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                 ",2408,2554);
$z[6][4]['type']="son";
$z[6][4]['typeid']="3";
$z[7]=Array("channel","\r\n                 <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                 ",2925,3072);
$z[7][4]['type']="son";
$z[7][4]['typeid']="17";
$z[8]=Array("list","\r\n              <li><span>[field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/]</span><a title=\"[field:title/]\" href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></li>\r\n              ",3623,3863);
$z[8][4]['pagesize']="20";
$z[8][4]['titlelen']="80";
$z[9]=Array("pagelist","",3937,4003);
$z[9][4]['listitem']="index,end,pre,next,pageno";
$z[9][4]['listsize']="7";
$z[10]=Array("include","",4205,4240);
$z[10][4]['filename']="foot.htm";

?>