<?php
$z[0]=Array("field","",49,68);
$z[0][4]['name']="title";
$z[1]=Array("field","",148,177);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",217,275);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("field","",831,853);
$z[3][4]['name']="typename";
$z[4]=Array("list","\r\n<dl>\r\n	<a href=\"view.php?aid=[field:id/]\">\r\n		<dt><img src=\"[field:litpic/]\" alt=\"[field:title/]\" width=\"50\" height=\"50\"></dt>\r\n		<dd><h3>[field:title/]</h3></dd>\r\n		<dd>[field:description function='cn_substr(@me,100)'/]...</dd>\r\n		<dd><span>‰Ø¿¿£∫<script src=\"/plus/count.php?view=yes&aid=[field:id/]&mid=[field:mid/]\" type='text/javascript' language=\"javascript\"></script></span></dd>\r\n	</a>\r\n</dl>\r\n",1438,1893);
$z[4][4]['pagesize']="20";
$z[4][4]['titlelen']="36";
$z[5]=Array("pagelist","",1932,1998);
$z[5][4]['listitem']="index,end,pre,next,pageno";
$z[5][4]['listsize']="2";
$z[6]=Array("arclist","\r\n	<div class=\"topic\">\r\n		<ul class=\"cont-list\">\r\n			<li>\r\n				<span class=\"live-icon\">[field:typename/]</span><a href=\"view.php?aid=[field:id/]\">[field:title/]</a>\r\n			</li>\r\n		</ul>\r\n	</div>\r\n    ",2077,2353);
$z[6][4]['titlelen']="36";
$z[6][4]['typeid']="24";
$z[6][4]['row']="3";
$z[6][4]['orderby']="rand";

?>