<?php
$z[0]=Array("field","",253,272);
$z[0][4]['name']="title";
$z[1]=Array("field","",352,381);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",421,479);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("global","",981,1007);
$z[3][4]['name']="cfg_cmspath";
$z[4]=Array("include","",1249,1285);
$z[4][4]['filename']="head2.htm";
$z[5]=Array("field","",1453,1475);
$z[5][4]['name']="position";
$z[6]=Array("channel","\r\n      <a title=\"[field:typename/]\" href=\"[field:typeurl/]\">[field:typename/]</a>\r\n      ",1602,1732);
$z[6][4]['type']="son";
$z[7]=Array("arclist","\r\n              <li><a title=\"[field:title/]\" href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a> <span>[field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/]</span></li>\r\n              ",2647,2901);
$z[7][4]['row']="10";
$z[7][4]['titlelen']="50";
$z[7][4]['typeid']="18";
$z[8]=Array("arclist","\r\n              <li><a title=\"[field:title/]\" href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a> <span>[field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/]</span></li>\r\n              ",3253,3507);
$z[8][4]['row']="10";
$z[8][4]['titlelen']="50";
$z[8][4]['typeid']="19";
$z[9]=Array("include","",3742,3777);
$z[9][4]['filename']="foot.htm";

?>